CREATE TABLE IF NOT EXISTS `DB_SISTEMA_HORARIOS`.`Estados` (
    `Estado_Id` TINYINT(2) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Estado_Descripcion` VARCHAR(50)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;