CREATE TABLE IF NOT EXISTS `DB_SISTEMA_HORARIOS`.`Paises` (
    `Pais_Id` TINYINT(3) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Pais_Nombre` VARCHAR(45)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;