CREATE TABLE IF NOT EXISTS `DB_SISTEMA_HORARIOS`.`PoliticaHoraria` (
    `PH_Id` SMALLINT(5) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `PH_HorarioFlexible` BIT(1),
    `PH_Nombre` VARCHAR(60),
    `PH_Estado` BIT(1) DEFAULT 1
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;