CREATE TABLE IF NOT EXISTS `DB_SISTEMA_HORARIOS`.`PoliticaHoraria_Detalle` (
    `PHD_Id` MEDIUMINT(6) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `PHD_PHId` SMALLINT(5) UNSIGNED NOT NULL,
    `PHD_DiaSemana` TINYINT(1) UNSIGNED,
    `PHD_HoraDesde` TIME,
    `PHD_HoraHasta` TIME,
    `PHD_Horas` TINYINT(2) UNSIGNED,
    KEY `IDX_FK_PHD_PH` (`PHD_PHId`),
    CONSTRAINT `FK_PHD_PH` FOREIGN KEY (`PHD_PHId`) REFERENCES `PoliticaHoraria` (`PH_Id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;