CREATE TABLE IF NOT EXISTS `DB_SISTEMA_HORARIOS`.`Categorias` (
    `Categ_Id` SMALLINT(4) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Categ_Nombre` VARCHAR(60)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;