CREATE TABLE IF NOT EXISTS `DB_SISTEMA_HORARIOS`.`Infracciones` (
    `Infrac_Id` SMALLINT(3) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Infrac_Nombre` VARCHAR(60)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;