CREATE TABLE IF NOT EXISTS `DB_SISTEMA_HORARIOS`.`Novedades` (
    `Noved_Id` SMALLINT(4) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Noved_Descripcion` VARCHAR(60)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;