CREATE TABLE IF NOT EXISTS `DB_SISTEMA_HORARIOS`.`Empleados` (
    `Emp_Id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Emp_EstadoId` TINYINT(2) UNSIGNED NOT NULL DEFAULT 1,
    `Emp_LocalId` INT UNSIGNED NOT NULL,
    `Emp_CategId` SMALLINT(4) UNSIGNED NOT NULL,
    `Emp_SectorId` SMALLINT(3) UNSIGNED NOT NULL,
    `Emp_PHId` SMALLINT(5) UNSIGNED NOT NULL,
    `Emp_Nombre` VARCHAR(100),
    `Emp_Apellido` VARCHAR(60),
    `Emp_FechaNac` DATE,
    `Emp_FechaAlta` DATE,
    `Emp_FechaBaja` DATE,
    `Emp_Domicilio` VARCHAR(150),
    `Emp_Email` VARCHAR(80),
    `Emp_Telefono` VARCHAR(20),
    `Emp_Salario` decimal(10, 2) UNSIGNED DEFAULT 0,
    KEY `IDX_FK_Emp_Estado` (`Emp_EstadoId`),
    KEY `IDX_FK_Emp_Local` (`Emp_LocalId`),
    KEY `IDX_FK_Emp_PH` (`Emp_PHId`),
    KEY `IDX_FK_Emp_Categ` (`Emp_CategId`),
    KEY `IDX_FK_Emp_Sector` (`Emp_SectorId`),
    CONSTRAINT `FK_Emp_Estado` FOREIGN KEY (`Emp_EstadoId`) REFERENCES `Estados` (`Estado_Id`),
    CONSTRAINT `FK_Emp_Local` FOREIGN KEY (`Emp_LocalId`) REFERENCES `Localidades` (`Local_Id`),
    CONSTRAINT `FK_Emp_PH` FOREIGN KEY (`Emp_PHId`) REFERENCES `PoliticaHoraria` (`PH_Id`),
    CONSTRAINT `FK_Emp_Categ` FOREIGN KEY (`Emp_CategId`) REFERENCES `Categorias` (`Categ_Id`),
    CONSTRAINT `FK_Emp_Sector` FOREIGN KEY (`Emp_SectorId`) REFERENCES `Sectores` (`Sector_Id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;